In [1]:
!pip install datasets

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 480.6/480.6 kB 24.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 13.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 179.3/179.3 kB 18.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.5/143.5 kB 6.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.8/194.8 kB 19.5 MB/s eta 0:00:00
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2024.10.0
    Uninstalling fsspec-2024.10.0:
      Successfully uninstalled fsspec-2024.10.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gcsfs 2024.10.0 requires fsspec==2024.10.0, but you have fsspec 2024.9.0 which is incompatible.
torch 2.5.1+cu124 requires nvidia-cublas-cu12==12.4.5.8; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cublas-cu12 12.5.3.2 wh

In [2]:
import tensorflow as tf
from transformers import TFAutoModel, AutoTokenizer
from datasets import load_dataset
from collections import Counter

In [3]:
model = TFAutoModel.from_pretrained("bert-base-uncased")

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.bias', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.weight']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions w

In [4]:
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

In [5]:
inputs = tokenizer(['Hello', 'How are you'], padding=True, truncation=True, return_tensors='tf')
inputs

{'input_ids': <tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[ 101, 7592,  102,    0,    0],
       [ 101, 2129, 2024, 2017,  102]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[1, 1, 1, 0, 0],
       [1, 1, 1, 1, 1]], dtype=int32)>}

In [6]:
output = model(inputs)
output

TFBaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=<tf.Tensor: shape=(2, 5, 768), dtype=float32, numpy=
array([[[-0.30609733,  0.26222885, -0.18961737, ..., -0.16511053,
          0.10138195,  0.4119023 ],
        [-0.73900914, -0.03363667,  0.3932195 , ..., -0.1818075 ,
         -0.18388602, -0.21847905],
        [ 0.5800885 ,  0.06270925, -0.2637223 , ...,  0.3963107 ,
         -0.56836957, -0.49242973],
        [-0.605158  ,  0.16286792,  0.36690637, ..., -0.08638733,
          0.13334492,  0.28940228],
        [-0.65102273, -0.01890645,  0.24940467, ..., -0.05653275,
          0.19524042,  0.21820325]],

       [[ 0.07747278,  0.04501358, -0.16765122, ..., -0.3346343 ,
          0.16396384,  0.12080589],
        [-0.02718119, -0.71175593, -0.29173535, ..., -0.12723064,
          0.6787842 , -0.5343534 ],
        [ 0.6442044 , -0.9804521 , -0.03809471, ..., -0.60107917,
          0.16867957, -0.49630743],
        [ 0.01914811, -0.7620813 ,  0.58827186, ..., -0.32224905

In [7]:
emotions = load_dataset('SetFit/emotion')

README.md:   0%|          | 0.00/194 [00:00<?, ?B/s]

Repo card metadata block was not found. Setting CardData to empty.


train.jsonl:   0%|          | 0.00/2.23M [00:00<?, ?B/s]

validation.jsonl:   0%|          | 0.00/276k [00:00<?, ?B/s]

test.jsonl:   0%|          | 0.00/279k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/16000 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/2000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/2000 [00:00<?, ? examples/s]

In [8]:
emotions

DatasetDict({
    train: Dataset({
        features: ['text', 'label', 'label_text'],
        num_rows: 16000
    })
    validation: Dataset({
        features: ['text', 'label', 'label_text'],
        num_rows: 2000
    })
    test: Dataset({
        features: ['text', 'label', 'label_text'],
        num_rows: 2000
    })
})

In [9]:
print("Sample Entries from the Training Dataset:")
print(emotions['train'][:5])

Sample Entries from the Training Dataset:
{'text': ['i didnt feel humiliated', 'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake', 'im grabbing a minute to post i feel greedy wrong', 'i am ever feeling nostalgic about the fireplace i will know that it is still on the property', 'i am feeling grouchy'], 'label': [0, 0, 3, 2, 3], 'label_text': ['sadness', 'sadness', 'anger', 'love', 'anger']}


In [10]:
train_labels = emotions['train']['label']
label_counts = Counter(train_labels)

In [11]:
print("\nLabel Distribution in Training Data:")
for label, count in label_counts.items():
    print(f"Label {label}: {count}")


Label Distribution in Training Data:
Label 0: 4666
Label 3: 2159
Label 2: 1304
Label 5: 572
Label 4: 1937
Label 1: 5362


In [12]:
def tokenize(batch): return tokenizer(batch['text'], padding=True, truncation=True, max_length=128)

In [13]:
emotions_encoded = emotions.map(tokenize, batched=True, batch_size=None)

Map:   0%|          | 0/16000 [00:00<?, ? examples/s]

Map:   0%|          | 0/2000 [00:00<?, ? examples/s]

Map:   0%|          | 0/2000 [00:00<?, ? examples/s]

In [14]:
emotions_encoded

DatasetDict({
    train: Dataset({
        features: ['text', 'label', 'label_text', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 16000
    })
    validation: Dataset({
        features: ['text', 'label', 'label_text', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 2000
    })
    test: Dataset({
        features: ['text', 'label', 'label_text', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 2000
    })
})

In [15]:
emotions_encoded.set_format('tf', columns=['input_ids', 'attention_mask', 'token_type_ids', 'label'])


BATCH_SIZE = 64

def order(inp):
    data = list(inp.values())
    return {
        'input_ids': data[1],
        'attention_mask': data[2],
        'token_type_ids': data[3]
    }, data[0]

# converting train split of `emotions_encoded` to tensorflow format
train_dataset = tf.data.Dataset.from_tensor_slices(emotions_encoded['train'][:])
# set batch_size and shuffle
train_dataset = train_dataset.batch(BATCH_SIZE).shuffle(1000)
# map the `order` function
train_dataset = train_dataset.map(order, num_parallel_calls=tf.data.AUTOTUNE)

# doing the same for test set
test_dataset = tf.data.Dataset.from_tensor_slices(emotions_encoded['test'][:])
test_dataset = test_dataset.batch(BATCH_SIZE)
test_dataset = test_dataset.map(order, num_parallel_calls=tf.data.AUTOTUNE)

In [16]:
inp, out = next(iter(train_dataset))
print(inp, '\n\n', out)

{'input_ids': <tf.Tensor: shape=(64, 87), dtype=int64, numpy=
array([[  101, 10047,  3110, ...,     0,     0,     0],
       [  101,  1045,  2428, ...,     0,     0,     0],
       [  101,  1045,  2031, ...,     0,     0,     0],
       ...,
       [  101,  1045,  2001, ...,     0,     0,     0],
       [  101,  1045,  2113, ...,     0,     0,     0],
       [  101,  1045,  3811, ...,     0,     0,     0]])>, 'attention_mask': <tf.Tensor: shape=(64, 87), dtype=int64, numpy=
array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])>, 'token_type_ids': <tf.Tensor: shape=(64, 87), dtype=int64, numpy=
array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]])>} 

 tf.Tensor(
[1 4 1 2 0 0 0 0 5 0 1 1 0 

In [37]:
from collections import Counter
import numpy as np
from sklearn.utils.class_weight import compute_class_weight

# Get class distribution
labels = emotions_encoded['train']['label']
# Convert the labels to a NumPy array to make it hashable
labels = np.array(labels)
class_weights = compute_class_weight(class_weight='balanced', classes=np.unique(labels), y=labels)
class_weights_dict = {i: weight for i, weight in enumerate(class_weights)}

print("Class Weights:", class_weights_dict)

Class Weights: {0: 0.5715102157451064, 1: 0.49732686808404825, 2: 2.044989775051125, 3: 1.2351397251814111, 4: 1.3766993632765445, 5: 4.662004662004662}


In [17]:
class BERTForClassification(tf.keras.Model):
    def __init__(self, bert_model, num_classes):
        super().__init__()
        self.bert = bert_model
        self.fc = tf.keras.layers.Dense(num_classes, activation='softmax')

    def call(self, inputs):
        x = self.bert(inputs)[1]
        return self.fc(x)

    def get_config(self):
        config = super().get_config()
        config.update({
            "num_classes": self.fc.units,  # Store number of output classes
        })
        return config

    @classmethod
    def from_config(cls, config):
        from transformers import TFBertModel  # Import BERT model
        bert_model = TFBertModel.from_pretrained("bert-base-uncased")  # Load base model again
        return cls(bert_model, config["num_classes"])

In [38]:
classifier = BERTForClassification(model, num_classes=6)

classifier.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-5),
    loss=tf.keras.losses.SparseCategoricalCrossentropy(),
    metrics=['accuracy']
)

In [39]:
history = classifier.fit(
    train_dataset,
    epochs=3,
    class_weight=class_weights_dict  # Apply computed class weights
)


Epoch 1/3
250/250 [==============================] - 321s 1s/step - loss: 0.3261 - accuracy: 0.9006
Epoch 2/3
250/250 [==============================] - 279s 1s/step - loss: 0.1409 - accuracy: 0.9426
Epoch 3/3
250/250 [==============================] - 279s 1s/step - loss: 0.1168 - accuracy: 0.9493


In [40]:
classifier.evaluate(test_dataset)

32/32 [==============================] - 12s 275ms/step - loss: 0.1909 - accuracy: 0.9305


[0.19094300270080566, 0.9304999709129333]

In [43]:
def test_emotions_with_label_text(texts, classifier, tokenizer):
    """
    Predicts the emotion of input texts and maps them to emotion labels directly.

    Args:
        texts (list): List of text strings to classify.
        classifier: Trained BERT classifier model.
        tokenizer: Tokenizer used during training.

    Returns:
        None. Prints out the text and its predicted emotion.
    """
    # Define explicit label mapping based on dataset index
    label_mapping = {
        0: "sadness",
        1: "joy",
        2: "love",
        3: "anger",
        4: "fear",
        5: "surprise"
    }

    # Tokenize the input text
    inputs = tokenizer(
        texts, padding=True, truncation=True, max_length=128, return_tensors="tf"
    )

    # Get predictions
    # The classifier outputs probabilities, not logits directly.
    probs = classifier(inputs)
    # We don't need to apply softmax again as it's already applied in the model.
    # probs = tf.nn.softmax(logits, axis=1)
    predictions = tf.argmax(probs, axis=1).numpy()  # Convert probabilities to predicted label indices

    # Map predictions to emotion labels
    predicted_emotions = [label_mapping[pred] for pred in predictions]

    # Print results
    print("\nPredicted Emotions:")
    for text, emotion in zip(texts, predicted_emotions):
        print(f"Text: '{text}' => Predicted Emotion: {emotion}")


# Example texts to classify
test_texts = [
    "I feel so empty inside.",
    "Damn shes a great girl to love",
    "I can't take this pain anymore.",
    "I don't want to be here anymore.",
    "Why does everything hurt so much?",
    "I feel so alone in this world.",
    "I just want to end my life",
    "I can't escape my thoughts.",
    "I am getting more creative now. I love what I do",
    "todays game was awesome. what a great dayyyy",
    "I am so happy about my life, what a joyful day ",
    "I love going out with him ",
    "I literally hate my life. I cant do this anymore",
    "I’m surrounded by people who care about me.",
    "I'm feeling hopeless about the future.",
    "I want to kill that person. I cant do this anymore"
]

# Call the function with the test texts
test_emotions_with_label_text(test_texts, classifier, tokenizer)


Predicted Emotions:
Text: 'I feel so empty inside.' => Predicted Emotion: sadness
Text: 'Damn shes a great girl to love' => Predicted Emotion: joy
Text: 'I can't take this pain anymore.' => Predicted Emotion: sadness
Text: 'I don't want to be here anymore.' => Predicted Emotion: fear
Text: 'Why does everything hurt so much?' => Predicted Emotion: sadness
Text: 'I feel so alone in this world.' => Predicted Emotion: sadness
Text: 'I just want to end my life' => Predicted Emotion: fear
Text: 'I can't escape my thoughts.' => Predicted Emotion: fear
Text: 'I am getting more creative now. I love what I do' => Predicted Emotion: joy
Text: 'todays game was awesome. what a great dayyyy' => Predicted Emotion: joy
Text: 'I am so happy about my life, what a joyful day ' => Predicted Emotion: joy
Text: 'I love going out with him ' => Predicted Emotion: love
Text: 'I literally hate my life. I cant do this anymore' => Predicted Emotion: sadness
Text: 'I’m surrounded by people who care about me.' => 

In [45]:
import tensorflow as tf
import shutil
from google.colab import files

# Define save paths
model_save_path = "bert_emotion_model"
tokenizer_save_path = "tokenizer"

# Save the model
classifier.save(model_save_path)

# Save the tokenizer
tokenizer.save_pretrained(tokenizer_save_path)

# Zip the model and tokenizer for download
shutil.make_archive(model_save_path, 'zip', model_save_path)
shutil.make_archive(tokenizer_save_path, 'zip', tokenizer_save_path)

# Download model and tokenizer
files.download(model_save_path + ".zip")
files.download(tokenizer_save_path + ".zip")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>